### ISSUE TITLE
NEI crash

### ISSUE THREAD

**Issue by carminaburana123** [Shukaro/Artifice#122]
When I press 'r', 'p' and some other keys when searching for sertain blocks in NEI the game freezes and crashes.

---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 21/10/15 14:54
Description: Unexpected error

java.lang.IllegalStateException: Already tesselating!
    at net.minecraft.client.renderer.Tessellator.func_78371_b(Tessellator.java:219)
    at net.minecraft.client.renderer.Tessellator.func_78382_b(Tessellator.java:212)
    at net.minecraft.client.shader.Framebuffer.func_147615_c(Framebuffer.java:252)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1034)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at net.minecraft.client.renderer.Tessellator.func_78371_b(Tessellator.java:219)
    at net.minecraft.client.renderer.Tessellator.func_78382_b(Tessellator.java:212)

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [EntityClientPlayerMP['isblimidar'/365, l='MpServer', x=4004,82, y=60,62, z=1358,28]]
    Chunk stats: MultiplayerChunkCache: 1089, 1089
    Level seed: 0
    Level generator: ID 04 - BIOMESOP, ver 0. Features enabled: false
    Level generator options: 
    Level spawn location: World: (197,64,968), Chunk: (at 5,4,8 in 12,60; contains blocks 192,0,960 to 207,255,975), Region: (0,1; contains chunks 0,32 to 31,63, blocks 0,0,512 to 511,255,1023)
    Level time: 181337 game time, 204696 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
    Forced entities: 17 total; [EntityBat['Bat'/385, l='MpServer', x=4043,78, y=19,00, z=1333,28], EntityBat['Bat'/387, l='MpServer', x=3947,38, y=41,81, z=1333,72], EntityDryad['Dryad'/388, l='MpServer', x=3982,34, y=64,00, z=1301,13], EntityBat['Bat'/392, l='MpServer', x=4078,52, y=13,71, z=1342,38], EntitySquid['Squid'/400, l='MpServer', x=4059,53, y=57,34, z=1423,41], EntitySquid['Squid'/402, l='MpServer', x=4061,50, y=55,00, z=1417,50], EntityPig['Pig'/403, l='MpServer', x=3934,22, y=73,00, z=1371,91], EntityPig['Pig'/404, l='MpServer', x=3927,38, y=65,00, z=1373,19], EntityBat['Bat'/920, l='MpServer', x=4051,16, y=13,18, z=1361,59], EntityPig['Pig'/409, l='MpServer', x=3937,56, y=66,00, z=1389,69], EntityBat['Bat'/921, l='MpServer', x=4054,25, y=12,71, z=1377,88], EntityPig['Pig'/410, l='MpServer', x=3932,13, y=72,00, z=1380,06], EntityBat['Bat'/922, l='MpServer', x=3934,72, y=22,00, z=1283,22], EntityBat['Bat'/923, l='MpServer', x=3935,13, y=22,43, z=1281,91], EntityClientPlayerMP['isblimidar'/365, l='MpServer', x=4004,82, y=60,62, z=1358,28], EntityBat['Bat'/380, l='MpServer', x=3978,63, y=14,10, z=1381,75], EntityBat['Bat'/383, l='MpServer', x=3977,67, y=40,86, z=1388,66]]
    Retry entities: 0 total; []
    Server brand: fml,forge
    Server type: Integrated singleplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:927)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 10 (amd64) version 10.0
    Java Version: 1.8.0_60, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 655376664 bytes (625 MB) / 1539715072 bytes (1468 MB) up to 6429081600 bytes (6131 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 95
    FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1448 60 mods loaded, 60 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAA   mcp{9.05} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJAAAA   FML{7.10.99.99} [Forge Mod Loader](forge-1.7.10-10.13.4.1448-1.7.10.jar) 
    UCHIJAAAA   Forge{10.13.4.1448} [Minecraft Forge](forge-1.7.10-10.13.4.1448-1.7.10.jar) 
    UCHIJAAAA   AM2-Preloader{0.0.2} [AMCore](minecraft.jar) 
    UCHIJAAAA   TooManyItems{1.7.10} [TooManyItems](minecraft.jar) 
    UCHIJAAAA   <CoFH ASM>{000} [CoFH ASM](minecraft.jar) 
    UCHIJAAAA   AnimationAPI{1.2.4} [AnimationAPI](AnimationAPI-1.7.10-1.2.4.jar) 
    UCHIJAAAA   arsmagica2{1.4.0.008} [Ars Magica 2](1.7.10_AM2-1.4.0.008 %281%29.jar) 
    UCHIJAAAA   securitycraft{v1.7.4.1} [SecurityCraft]([1.7.10] SecurityCraft v1.7.4.1.jar) 
    UCHIJAAAA   Mantle{1.7.10-0.3.2.jenkins184} [Mantle](Mantle-1.7.10-0.3.2.jar) 
    UCHIJAAAA   Natura{2.2.0} [Natura]([1.7.10][Natura][v2.2.0.1].jar) 
    UCHIJAAAA   BiomesOPlenty{2.1.0} [Biomes O' Plenty]([1.7.10][BiomesOPlenty][v2.1.0.1067].jar) 
    UCHIJAAAA   ExtrabiomesXL{3.16.3} [ExtrabiomesXL]([1.7.10][ExtraBiomesXL][v3.16.3].jar) 
    UCHIJAAAA   morematerials{0.9.20150201.0} [More Materials]([1.7.10][MoreMaterials][v1.1.1].jar) 
    UCHIJAAAA   TwilightForest{2.3.7} [The Twilight Forest]([1.7.10][TwilightForest][v2.3.7].jar) 
    UCHIJAAAA   bspkrsCore{6.16} [bspkrsCore]([1.7.10]bspkrsCore-universal-6.16.jar) 
    UCHIJAAAA   Treecapitator{1.7.10} [Treecapitator]([1.7.10]Treecapitator-universal-2.0.4.jar) 
    UCHIJAAAA   Highlands{2.2.3} [Highlands]([1.7.2][Highlands][v2.2.3].jar) 
    UCHIJAAAA   adventurebackpack{1.7.10-0.8b} [Adventure Backpack](adventurebackpack-1.7.10-0.8b.jar) 
    UCHIJAAAA   CoFHCore{1.7.10R3.0.2} [CoFH Core](CoFHCore-[1.7.10]3.0.2-262.jar) 
    UCHIJAAAA   Artifice{1.7.10R1.1.4} [Artifice](Artifice-1.7.10-1.1.5R-399.jar) 
    UCHIJAAAA   BiblioCraft{1.11.2} [BiblioCraft](BiblioCraft[v1.11.2][MC1.7.10].jar) 
    UCHIJAAAA   BiblioWoodsBoP{1.9} [BiblioWoods Biomes O'Plenty Edition](BiblioWoods[BiomesOPlenty][v1.9].jar) 
    UCHIJAAAA   BiblioWoodsEBXL{1.4} [BiblioWoods ExtraBiomesXL Edition](BiblioWoods[ExtraBiomesXL][v1.4].jar) 
    UCHIJAAAA   BiblioWoodsHighlands{1.4} [BiblioWoods Highlands Edition](BiblioWoods[Highlands][v1.4].jar) 
    UCHIJAAAA   BiblioWoodsNatura{1.5} [BiblioWoods Natura Edition](BiblioWoods[Natura][v1.5].jar) 
    UCHIJAAAA   CarpentersBlocks{3.3.7} [Carpenter's Blocks](Carpenter's Blocks v3.3.7 - MC 1.7.10.jar) 
    UCHIJAAAA   chocolateQuest{1.0} [Chocolate Quest](chocolateQuest-1.7.10-1.0.jar) 
    UCHIJAAAA   Enchiridion{1.1} [Enchiridion](Enchiridion-1.7.X-1.2b.jar) 
    UCHIJAAAA   ForgeMultipart{1.2.0.345} [Forge Multipart](ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
    UCHIJAAAA   ExtraUtilities{1.2.11} [Extra Utilities](extrautilities-1.2.11.jar) 
    UCHIJAAAA   ForgeRelocation{0.0.1.4} [ForgeRelocation](ForgeRelocation-0.0.1.4-universal.jar) 
    UCHIJAAAA   MCFrames{1.0} [MCFrames](ForgeRelocation-0.0.1.4-universal.jar) 
    UCHIJAAAA   RelocationFMP{0.0.1.2} [RelocationFMP](ForgeRelocationFMP-0.0.1.2-universal.jar) 
    UCHIJAAAA   inventorytweaks{1.58-147-645ca10} [Inventory Tweaks](InventoryTweaks-1.58-147.jar) 
    UCHIJAAAA   IronChest{6.0.60.741} [Iron Chest](ironchest-1.7.10-6.0.60.741-universal.jar) 
    UCHIJAAAA   journeymap{@JMVERSION@} [JourneyMap](journeymap-1.7.10-5.1.0-unlimited.jar) 
    UCHIJAAAA   RadixCore{2.0.2} [RadixCore](RadixCore-2.0.2-1.7.10-universal.jar) 
    UCHIJAAAA   MCA{1.7.10-5.0.7.2} [Minecraft Comes Alive](MCA-1.7.10-5.0.7.2-universal.jar) 
    UCHIJAAAA   cfm{3.4.8} [§9MrCrayfish's Furniture Mod](MrCrayfishFurnitureModv3.4.8%281.7.10%29.jar) 
    UCHIJAAAA   MrTJPCoreMod{1.1.0.31} [MrTJPCore](MrTJPCore-1.1.0.31-universal.jar) 
    UCHIJAAAA   noCubes{1.0} [No Cubes](noCubes-1.0.jar) 
    UCHIJAAAA   ProjRed|Core{4.7.0pre9.92} [ProjectRed Core](ProjectRed-1.7.10-4.7.0pre9.92-Base.jar) 
    UCHIJAAAA   ProjRed|Transmission{4.7.0pre9.92} [ProjectRed Transmission](ProjectRed-1.7.10-4.7.0pre9.92-Integration.jar) 
    UCHIJAAAA   ProjRed|Transportation{4.7.0pre9.92} [ProjectRed Transportation](ProjectRed-1.7.10-4.7.0pre9.92-Mechanical.jar) 
    UCHIJAAAA   ProjRed|Exploration{4.7.0pre9.92} [ProjectRed Exploration](ProjectRed-1.7.10-4.7.0pre9.92-World.jar) 
    UCHIJAAAA   ProjRed|Compatibility{4.7.0pre9.92} [ProjectRed Compatibility](ProjectRed-1.7.10-4.7.0pre9.92-Compat.jar) 
    UCHIJAAAA   ProjRed|Integration{4.7.0pre9.92} [ProjectRed Integration](ProjectRed-1.7.10-4.7.0pre9.92-Integration.jar) 
    UCHIJAAAA   ProjRed|Fabrication{4.7.0pre9.92} [ProjectRed Fabrication](ProjectRed-1.7.10-4.7.0pre9.92-Fabrication.jar) 
    UCHIJAAAA   ProjRed|Illumination{4.7.0pre9.92} [ProjectRed Illumination](ProjectRed-1.7.10-4.7.0pre9.92-Lighting.jar) 
    UCHIJAAAA   ProjRed|Expansion{4.7.0pre9.92} [ProjectRed Expansion](ProjectRed-1.7.10-4.7.0pre9.92-Mechanical.jar) 
    UCHIJAAAA   secretroomsmod{4.7.1} [The SecretRoomsMod](secretroomsmod-1.7.10-4.7.1.406 %281%29.jar) 
    UCHIJAAAA   smoothbedrock{2.2.0.9} [SmoothBedrock](SmoothBedrock-1.7.10-2.2.0.9.jar) 
    UCHIJAAAA   staircraftmod{1.7} [Staircraft](Staircraftmod 1.7 - 1.7.10 Forge.jar) 
    UCHIJAAAA   Waila{1.5.10} [Waila](Waila-1.5.10_1.7.10.jar) 
    UCHIJAAAA   weaponmod{v1.14.3} [Balkon's WeaponMod](weaponmod-1.14.3.jar) 
    UCHIJAAAA   worldedit{6.0-beta-01} [WorldEdit](worldedit-forge-mc1.7.10-6.0-beta-01.jar) 
    UCHIJAAAA   Ztones{1.7.10} [Ztones](Ztones-1.7.10-2.2.1.jar) 
    UCHIJAAAA   McMultipart{1.2.0.345} [Minecraft Multipart Plugin](ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
    UCHIJAAAA   ForgeMicroblock{1.2.0.345} [Forge Microblocks](ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
    GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 355.98' Renderer: 'GeForce GTX 970M/PCIe/SSE2'
    Mantle Environment: Environment healthy.
    CoFHCore: -[1.7.10]3.0.2-262
    Launched Version: 1.7.10-Forge10.13.4.1448-1.7.10
    LWJGL: 2.9.1
    OpenGL: GeForce GTX 970M/PCIe/SSE2 GL version 4.5.0 NVIDIA 355.98, NVIDIA Corporation
    GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

```
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: []
Current Language: English (US)
Profiler Position: N/A (disabled)
Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
Anisotropic Filtering: On (8)
```

**Comment by carminaburana123** [comment]
Nevermind fixed it myself
